require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.nerdtree"
require "user.neoterm"

require "user.cmp"
require "user.lsp"
require "user.treesitter"
